services:
  - type: web
    name: videohub
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: videohub-db
          property: connectionString
    disk:
      name: videohub-disk
      mountPath: /opt/render/project/src/uploads
      sizeGB: 1

databases:
  - name: videohub-db
    databaseName: videohub
    user: videohub
    plan: free
    region: oregon
    postgresMajorVersion: 16

volumes:
  - name: videohub-disk
    sizeGB: 1